#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

if [[ $# -ne 1 ]]; then
   echo "Usage: $0 <filename>"
   echo ""

   exit 1
fi

if [[ ! -f "$1" ]]; then
   echo "$1 does not exist!"
   echo ""

   exit 1
fi

sum=$(awk '{print $2}' "$1" | paste -sd+ | bc); echo "$sum / $(cat $1 | wc -l)" | bc -l

exit 0
