#!/bin/bash

# TODO: Parameterize whether to run for Wordle or Wordmaster
# TODO: Sort results by rounds needed
# TODO: Save results to disk

set -o nounset
# set -o errexit
set -o pipefail

while read ONE_WORD
do
   words $ONE_WORD > /dev/null
   ROUNDS=$?

   echo -n $ONE_WORD
   echo -n " "

   if [[ $ROUNDS == 254 ]]; then
      echo FAILURE!!!

      exit 1
   fi

   echo $ROUNDS;
done < wordle-answers-alphabetical.txt
# done < wordmaster-answers-alphabetical.txt

exit 0
